baseURL = "https://top5rated.in/"
languageCode = "en-us"
title = "Top5Rated.in - Best Product Picks for Smart Shoppers"
theme = "top5rated-theme"

[params]
  description = "Top 5 rated gadgets, home appliances, and more. Updated regularly to help you buy smarter."
