name = "custom"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Custom theme for Top5Rated.in"
homepage = "https://top5rated.in"
tags = ["product", "blog", "top5", "custom"]
min_version = "0.100.0"